import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { analyzeDriver, type DriverAnalysis } from '@/utils/lapAnalysisAI';
import { DriverLapStats, formatLapTimeSeconds } from '@/lib/dataParser';
import { Download, TrendingUp, TrendingDown, AlertCircle, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';

interface DriverReportProps {
  driver: DriverLapStats;
}

export function DriverReport({ driver }: DriverReportProps) {
  const [analysis, setAnalysis] = useState<DriverAnalysis | null>(null);
  const { toast } = useToast();

  const generateReport = () => {
    const newAnalysis = analyzeDriver(driver);
    setAnalysis(newAnalysis);
    toast({
      title: 'Report Generated',
      description: `AI analysis complete for ${newAnalysis.driverName}`,
    });
  };

  const downloadReport = () => {
    if (!analysis) return;

    const reportText = `
==============================================
F1 DRIVER PERFORMANCE REPORT
==============================================

Driver: ${analysis.driverName}
Overall Rating: ${analysis.overallRating}/100

----------------------------------------------
PERFORMANCE STATISTICS
----------------------------------------------
Best Lap: ${formatLapTimeSeconds(driver.bestLap)}
Average Lap: ${formatLapTimeSeconds(driver.averageLap)}
Total Laps: ${driver.totalLaps}
Best Laps Recorded: ${driver.bestLaps.length}

----------------------------------------------
STRENGTHS
----------------------------------------------
${analysis.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

----------------------------------------------
WEAKNESSES
----------------------------------------------
${analysis.weaknesses.map((w, i) => `${i + 1}. ${w}`).join('\n')}

----------------------------------------------
KEY INSIGHTS
----------------------------------------------
${analysis.insights.map((insight, i) => `
${i + 1}. [${insight.severity.toUpperCase()}] ${insight.message}
   Category: ${insight.category}
   Type: ${insight.type}
`).join('\n')}

----------------------------------------------
RECOMMENDATIONS
----------------------------------------------
${analysis.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

==============================================
Generated by F1 Telemetry Analytics AI
==============================================
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `driver_report_${driver.number}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: 'Report Downloaded',
      description: 'Performance report saved successfully',
    });
  };

  const downloadJSON = () => {
    if (!analysis) return;

    const reportData = {
      driver: {
        number: driver.number,
        vehicle: driver.vehicle,
        class: driver.class,
      },
      statistics: {
        bestLap: driver.bestLap,
        averageLap: driver.averageLap,
        totalLaps: driver.totalLaps,
        bestLapsCount: driver.bestLaps.length,
      },
      analysis: {
        overallRating: analysis.overallRating,
        strengths: analysis.strengths,
        weaknesses: analysis.weaknesses,
        insights: analysis.insights,
        recommendations: analysis.recommendations,
      },
      timestamp: new Date().toISOString(),
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `driver_analysis_${driver.number}_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: 'JSON Downloaded',
      description: 'Analysis data exported successfully',
    });
  };

  const getInsightIcon = (type: string) => {
    switch (type) {
      case 'positive':
        return <CheckCircle2 className="h-4 w-4 text-green-400" />;
      case 'negative':
        return <TrendingDown className="h-4 w-4 text-red-400" />;
      default:
        return <AlertCircle className="h-4 w-4 text-yellow-400" />;
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'high':
        return 'bg-red-500/20 text-red-400 border-red-500/50';
      case 'medium':
        return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/50';
      default:
        return 'bg-blue-500/20 text-blue-400 border-blue-500/50';
    }
  };

  return (
    <Card className="w-full bg-background/95 backdrop-blur border-primary/20 p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
            AI Driver Performance Report
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            #{driver.number} - {driver.vehicle} ({driver.class})
          </p>
        </div>
        <div className="flex gap-2">
          {!analysis ? (
            <Button onClick={generateReport} variant="default">
              <TrendingUp className="mr-2 h-4 w-4" />
              Generate Report
            </Button>
          ) : (
            <>
              <Button onClick={downloadReport} variant="outline" size="sm">
                <Download className="mr-2 h-4 w-4" />
                Download TXT
              </Button>
              <Button onClick={downloadJSON} variant="outline" size="sm">
                <Download className="mr-2 h-4 w-4" />
                Export JSON
              </Button>
            </>
          )}
        </div>
      </div>

      {!analysis ? (
        <div className="text-center py-12 border-2 border-dashed border-border rounded-lg">
          <TrendingUp className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
          <p className="text-muted-foreground mb-4">
            Generate an AI-powered performance analysis for this driver
          </p>
          <Button onClick={generateReport} variant="default">
            Start Analysis
          </Button>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Overall Rating */}
          <div className="p-6 bg-primary/10 rounded-lg border border-primary/20">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-lg font-semibold text-foreground">Overall Performance Rating</h3>
              <span className="text-3xl font-bold text-primary">{analysis.overallRating}/100</span>
            </div>
            <Progress value={analysis.overallRating} className="h-3" />
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-3 gap-4">
            <div className="p-4 bg-background/50 rounded-lg border border-border">
              <p className="text-xs text-muted-foreground mb-1">Best Lap</p>
              <p className="text-xl font-bold text-foreground">{formatLapTimeSeconds(driver.bestLap)}</p>
            </div>
            <div className="p-4 bg-background/50 rounded-lg border border-border">
              <p className="text-xs text-muted-foreground mb-1">Average Lap</p>
              <p className="text-xl font-bold text-foreground">{formatLapTimeSeconds(driver.averageLap)}</p>
            </div>
            <div className="p-4 bg-background/50 rounded-lg border border-border">
              <p className="text-xs text-muted-foreground mb-1">Total Laps</p>
              <p className="text-xl font-bold text-foreground">{driver.totalLaps}</p>
            </div>
          </div>

          {/* Strengths & Weaknesses */}
          <div className="grid grid-cols-2 gap-4">
            <div className="p-4 bg-green-500/10 rounded-lg border border-green-500/20">
              <h3 className="font-semibold text-green-400 mb-3 flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4" />
                Strengths
              </h3>
              <ul className="space-y-2">
                {analysis.strengths.map((strength, idx) => (
                  <li key={idx} className="text-sm text-muted-foreground flex items-start gap-2">
                    <span className="text-green-400 mt-0.5">•</span>
                    {strength}
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-4 bg-red-500/10 rounded-lg border border-red-500/20">
              <h3 className="font-semibold text-red-400 mb-3 flex items-center gap-2">
                <TrendingDown className="h-4 w-4" />
                Areas to Improve
              </h3>
              <ul className="space-y-2">
                {analysis.weaknesses.map((weakness, idx) => (
                  <li key={idx} className="text-sm text-muted-foreground flex items-start gap-2">
                    <span className="text-red-400 mt-0.5">•</span>
                    {weakness}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Insights */}
          <div>
            <h3 className="font-semibold text-foreground mb-3">Key Insights</h3>
            <div className="space-y-2">
              {analysis.insights.map((insight, idx) => (
                <div
                  key={idx}
                  className="p-3 bg-background/50 rounded-lg border border-border flex items-start gap-3"
                >
                  {getInsightIcon(insight.type)}
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <Badge variant="outline" className={getSeverityColor(insight.severity)}>
                        {insight.severity}
                      </Badge>
                      <Badge variant="outline">{insight.category}</Badge>
                    </div>
                    <p className="text-sm text-muted-foreground">{insight.message}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Recommendations */}
          <div className="p-4 bg-primary/10 rounded-lg border border-primary/20">
            <h3 className="font-semibold text-foreground mb-3">Recommendations</h3>
            <ol className="space-y-2">
              {analysis.recommendations.map((rec, idx) => (
                <li key={idx} className="text-sm text-muted-foreground flex gap-2">
                  <span className="text-primary font-semibold">{idx + 1}.</span>
                  {rec}
                </li>
              ))}
            </ol>
          </div>
        </div>
      )}
    </Card>
  );
}
